### ISSUE TITLE
Returns None for empty models

### ISSUE THREAD

**Issue by MarkusRabe** [mvcisback/py-aiger-sat#3]
https://github.com/mvcisback/py-aiger-sat/blob/537819875f8031c8230903b556abd08c6ee115c5/aiger_sat/sat.py#L82

If the UNSAT core is empty (i.e. none of the assumptions were necessary to prove UNSAT) this method returns None. This can be unexpected. A better output would be the empty dictionary.

**Comment by mvcisback** [comment]
That makes sense.

It's technically a non-backwards compatible change, so I'll change and bump the major version.

**Comment by mvcisback** [comment]
Pushed and integrated into `3.0.0`
