### ISSUE TITLE
Wrong dependency?

### ISSUE THREAD

**Issue by alexeyignatiev** [mvcisback/py-aiger-sat#4]
Hi @mvcisback,

Is there any particular reason to depend on a specific version of `python-sat`? I mean the dependency on version `"0.1.5.dev13"` looks like a bug because newer versions `python-sat` can't be installed together with `py-aiger-sat` and vice versa.

**Comment by alexeyignatiev** [comment]
Actually, this dependency seems to appear in other related packages, e.g. `py-aiger-cnf`.

**Comment by alexeyignatiev** [comment]
OK, `py-aiger-cnf` looks okay as it does not depend on a fixed version. So the problem is perhaps only here.

**Comment by mvcisback** [comment]
@alexeyignatiev sorry about that. I'll look into it.

**Comment by mvcisback** [comment]
@alexeyignatiev Maybe, I'm missing something, but `py-aiger-cnf` lists `py-aiger-sat` as a development dependency.

   https://github.com/mvcisback/py-aiger-cnf/blob/master/pyproject.toml#L26

Unless I'm missing something, this should break the dependency chain. How are you installing `py-aiger-cnf`? If using `pip`, it should only require non-development dependencies. If using `poetry`, you need to give the `--no-dev` flag.

If this is an issue with `poetry's` packaging, I can temporarily remove the `py-aiger-sat` development dependency while I look into it more (probably in the evening PST).

**Comment by alexeyignatiev** [comment]
@mvcisback no, what I mean is that `py-aiger-sat` has `python-sat==0.1.5.dev13` as a dependency (not a development one).

There is no problem with `py-aiger-cnf`. Sorry for the confusion.

**Comment by mvcisback** [comment]
ah, thank you for pointing that out. I will try relaxing the version constraint and updating the the latest version and report back later (PST).

**Comment by mvcisback** [comment]
@alexeyignatiev I've just relaxed `py-aiger-sat`'s dependency and updated the locked version to `0.1.6.dev5`.

I will update `py-aiger-cnf` accordingly. Please let me know if you ave any more issues. I skimmed the referenced issue. In the worst case I'm willing to remove the `py-aiger-sat` development dependency in `py-aiger-cnf`. It is just used in a few tests, and could be replaced with enumeration.

**Comment by alexeyignatiev** [comment]
@mvcisback thanks a lot for the fix! It works now. To be honest, I have no idea why the issue arised on repl.it in the first place - PySAT does not depend on `py-aiger-sat` and yet repl.it tries to install `py-aiger-sat` if I want to use PySAT. Weird...
